##############################################################
# 
# Copyright (C) 2021-2021 Intel Corporation.
# SPDX-License-Identifier: MIT
# 
##############################################################
#
# This file includes all the test targets as well as all the
# non-default build rules and test recipes.
#
##############################################################


##############################################################
#
# Test targets
#
##############################################################

###### Place all generic definitions here ######

# Define the SDE example pin tools to build
SDE_TOOLS := 
PINPLAY_TOOLS := 

ifneq ($(OS),Windows_NT)
PINPLAY_TOOLS += loop-profiler loop-tracker looppoint
endif

OBJECT_ROOTS := global_isimpoint_inst
# This defines any static libraries (archives), that need to be built.
LIB_ROOTS := libglobalprofiler

##############################################################
#
# Build rules
#
##############################################################

# See makefile.default.rules for the default build rules.
TOOL_CXXFLAGS += -DSDE_INIT -DPINPLAY -I$(SDE_ROOT)/include -I$(PINPLAY_ROOT)/include

ifeq ($(OS),Windows_NT)
TOOL_LPATHS += /LIBPATH:$(SDE_ROOT)/lib/$(TARGET) /LIBPATH:$(PINPLAY_ROOT)/$(TARGET)
TOOL_LPATHS += libpinplay.lib libsde.lib bz2.lib zlib.lib
else
# sde and pinplay libraries appears twice to avoid circular dependency
TOOL_LPATHS += -L$(SDE_ROOT)/lib/$(TARGET) -L$(PINPLAY_ROOT)/$(TARGET)
TOOL_LPATHS += -lpinplay -lsde -lpinplay -lsde -lbz2 -lzlib
endif

###### Special libs' build rules ######

$(OBJDIR)libglobalprofiler$(LIB_SUFFIX): $(OBJDIR)global_isimpoint_inst$(OBJ_SUFFIX)
	$(ARCHIVER)$@ $^
	cp $(OBJDIR)libglobalprofiler$(LIB_SUFFIX) $(SDE_ROOT)/lib/$(TARGET)


